"""Health Passport — a one-page, printable summary for a new doctor.

Pocket version of Appointment Prep: instead of a full question agenda, this
renders the four things a clinician needs in the first 60 seconds of a visit —
active medications, allergies, key conditions, and recent abnormal labs — on a
single A4 page, as a real PDF.

Data discipline (same as the rest of the product):
  * "active medications" uses the deterministic activity windows
    (medication_activity.filter_active_timeline) so a 7-day antibiotic from
    last year is NOT listed as a current medicine;
  * allergies and conditions come straight from the extracted timeline;
  * abnormal labs are the recorded high/low flags, newest first;
  * nothing here is generated by a model and nothing is diagnosed.

Rendering uses PyMuPDF (``fitz``), which is already a dependency for document
reading, so no new package is required. Helvetica base-14 fonts keep the PDF
tiny and universally printable. ``build_health_passport_pdf`` raises a clear
RuntimeError when PyMuPDF is unavailable so the API can translate it to a 500.
"""

from __future__ import annotations

import logging
from datetime import date
from typing import Any, Dict, List, Optional

logger = logging.getLogger("health_passport")

# A4 portrait, in points.
PAGE_WIDTH = 595.3
PAGE_HEIGHT = 841.9
MARGIN = 44.0
CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN
FOOTER_RESERVE = 46.0

# Palette (r, g, b) floats in 0..1.
INK = (0.10, 0.16, 0.18)
MUTED = (0.40, 0.46, 0.50)
ACCENT = (0.05, 0.45, 0.42)
ACCENT_LIGHT = (0.92, 0.97, 0.96)
RED = (0.72, 0.20, 0.18)
RED_LIGHT = (0.99, 0.95, 0.95)
VIOLET = (0.42, 0.33, 0.60)
VIOLET_LIGHT = (0.97, 0.95, 0.99)

TITLE_FONT = "hebo"  # Helvetica-Bold
BODY_FONT = "helv"  # Helvetica


def _display_name(med: Dict[str, Any]) -> str:
    name = str(med.get("name") or "").strip()
    if name:
        return name
    ingredients = [str(i).strip() for i in (med.get("ingredients") or []) if str(i).strip()]
    return " / ".join(ingredients) or "unknown medication"


def _medication_line(med: Dict[str, Any]) -> str:
    dose = str(med.get("dosage") or "").strip()
    frequency = str(med.get("frequency") or "").strip()
    detail = " ".join(part for part in (dose, frequency) if part)
    name = _display_name(med)
    return f"{name}: {detail}" if detail else name


def _most_common_patient_name(timeline: Dict[str, Any]) -> Optional[str]:
    counts: Dict[str, List[Any]] = {}
    for visit in timeline.get("visits") or []:
        raw = str(visit.get("patient_name") or "").strip()
        if not raw:
            continue
        key = raw.lower()
        bucket = counts.setdefault(key, [raw, 0])
        bucket[1] += 1
    if not counts:
        return None
    return sorted(counts.values(), key=lambda item: (-item[1], item[0]))[0][0]


def _active_medication_lines(timeline: Dict[str, Any]) -> List[str]:
    try:
        from medication_activity import filter_active_timeline

        entries = (filter_active_timeline(timeline) or {}).get("medications_timeline") or []
    except Exception as exc:  # defensive — never fail the passport over activity windows
        logger.warning("activity windows unavailable, using full medication list: %s", exc)
        entries = timeline.get("medications_timeline") or []
    seen: set[str] = set()
    lines: List[str] = []
    for med in entries:
        if not isinstance(med, dict):
            continue
        key = _display_name(med).lower()
        if key in seen:
            continue
        seen.add(key)
        lines.append(_medication_line(med))
    return lines


def _condition_lines(timeline: Dict[str, Any]) -> List[str]:
    entries = timeline.get("diagnoses_timeline") or []
    # Active/confirmed conditions first; the rest are still shown if there is room.
    rank = {"active": 0, "confirmed": 0}
    ordered = sorted(
        (entry for entry in entries if isinstance(entry, dict)),
        key=lambda entry: rank.get(str(entry.get("status") or "").lower(), 1),
    )
    seen: set[str] = set()
    lines: List[str] = []
    for entry in ordered:
        name = str(entry.get("name") or "").strip()
        if not name or name.lower() in seen:
            continue
        seen.add(name.lower())
        lines.append(name)
    return lines


def _recent_abnormal_labs(timeline: Dict[str, Any], limit: int = 6) -> List[str]:
    entries = timeline.get("lab_results_timeline") or []
    abnormal = [
        entry
        for entry in entries
        if isinstance(entry, dict) and str(entry.get("flag") or "").lower() in ("high", "low")
    ]
    seen: set[str] = set()
    lines: List[str] = []
    # The timeline is chronological (oldest first); iterate newest-first so the
    # most recent reading of each test wins.
    for entry in reversed(abnormal):
        test = str(entry.get("test_name") or "").strip()
        if not test or test.lower() in seen:
            continue
        seen.add(test.lower())
        value = str(entry.get("value") or "").strip()
        unit = str(entry.get("unit") or "").strip()
        flag = str(entry.get("flag") or "").upper()
        reading = " ".join(part for part in (value, unit) if part)
        lines.append(
            f"{test}: {reading} (flagged {flag})" if reading else f"{test} (flagged {flag})"
        )
        if len(lines) >= limit:
            break
    return lines


def build_passport_data(
    timeline: Dict[str, Any],
    cross_check: Optional[Dict[str, Any]] = None,
    lab_trends: Optional[Dict[str, Any]] = None,
    patient_name: Optional[str] = None,
    workspace_name: Optional[str] = None,
) -> Dict[str, Any]:
    """Distil the record into the passport sections. Pure — no PDF work."""
    del cross_check, lab_trends  # reserved for future safety-signal lines
    return {
        "patient_name": (patient_name or "").strip()
        or _most_common_patient_name(timeline)
        or "Not recorded",
        "workspace_name": (workspace_name or "").strip() or None,
        "generated_at": date.today().isoformat(),
        "active_medications": _active_medication_lines(timeline),
        "allergies": [
            str(a).strip() for a in (timeline.get("known_allergies") or []) if str(a).strip()
        ],
        "conditions": _condition_lines(timeline),
        "recent_abnormal_labs": _recent_abnormal_labs(timeline),
    }


# ---------------------------------------------------------------------------
# PDF rendering
# ---------------------------------------------------------------------------


def _wrap(text: str, fontname: str, fontsize: float, max_width: float, fitz: Any) -> List[str]:
    """Word-wrap `text` to `max_width` using PyMuPDF's text measurement."""
    words = text.split()
    lines: List[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        width = fitz.get_text_length(candidate, fontname=fontname, fontsize=fontsize)
        if not current or width <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _draw_section(
    page: Any,
    fitz: Any,
    y: float,
    title: str,
    items: List[str],
    accent: Any,
    accent_light: Any,
    empty_text: str = "None recorded",
) -> float:
    """Draw one section, wrapping to the content width, and return the new Y.

    Keeps the whole page to one sheet: if the section would overflow the
    footer reserve, items are dropped and a "+N more" line is appended.
    """
    line_height = 12.6
    gap_after = 14.0
    bottom = PAGE_HEIGHT - FOOTER_RESERVE

    # Section heading.
    if y + 13 > bottom:
        return y
    page.insert_text(
        (MARGIN, y + 9.0),
        title,
        fontname=TITLE_FONT,
        fontsize=10.5,
        color=accent,
    )
    y += 15.0

    body_lines: List[str] = []
    shown = 0
    truncated = False
    for item in items:
        wrapped = _wrap(f"\u2022  {item}", BODY_FONT, 9.3, CONTENT_WIDTH, fitz)
        if y + (len(body_lines) + len(wrapped)) * line_height > bottom:
            truncated = True
            break
        body_lines.extend(wrapped)
        shown += 1

    if not body_lines:
        empty = _wrap(f"\u2022  {empty_text}", BODY_FONT, 9.3, CONTENT_WIDTH, fitz)
        if y + len(empty) * line_height <= bottom:
            body_lines = empty

    if truncated and shown < len(items):
        more = _wrap(
            f"\u2022  +{len(items) - shown} more not shown",
            BODY_FONT,
            9.3,
            CONTENT_WIDTH,
            fitz,
        )
        if y + (len(body_lines) + len(more)) * line_height <= bottom:
            body_lines.extend(more)

    for line in body_lines:
        page.insert_text(
            (MARGIN, y + 9.0),
            line,
            fontname=BODY_FONT,
            fontsize=9.3,
            color=INK,
        )
        y += line_height
    return y + gap_after


def render_passport_pdf(data: Dict[str, Any]) -> bytes:
    """Render the passport as a single-page PDF and return its bytes."""
    try:
        import fitz  # PyMuPDF
    except Exception as exc:  # pragma: no cover - environment-specific
        raise RuntimeError(
            "PyMuPDF is required to generate the health passport PDF but could not be imported."
        ) from exc

    doc = fitz.open()
    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)

    # Header band.
    header_h = 74.0
    page.draw_rect(
        fitz.Rect(0, 0, PAGE_WIDTH, header_h),
        color=None,
        fill=ACCENT_LIGHT,
        width=0,
    )
    page.insert_text(
        (MARGIN, 40.0),
        "Health Passport",
        fontname=TITLE_FONT,
        fontsize=20.0,
        color=INK,
    )
    page.insert_text(
        (MARGIN, 55.0),
        "A one-page summary of my health for a new doctor",
        fontname=BODY_FONT,
        fontsize=9.5,
        color=MUTED,
    )
    patient = str(data.get("patient_name") or "Not recorded")
    prepared = f"Prepared {data.get('generated_at', '')}"
    page.insert_text(
        (MARGIN, 69.0),
        f"Patient: {patient}",
        fontname=TITLE_FONT,
        fontsize=10.0,
        color=INK,
    )
    prepared_width = fitz.get_text_length(prepared, fontname=BODY_FONT, fontsize=8.5)
    page.insert_text(
        (PAGE_WIDTH - MARGIN - prepared_width, 69.0),
        prepared,
        fontname=BODY_FONT,
        fontsize=8.5,
        color=MUTED,
    )

    y = header_h + 10.0
    sections = [
        (
            "Active medications",
            data.get("active_medications") or [],
            ACCENT,
            ACCENT_LIGHT,
            "No active medications on record",
        ),
        (
            "Allergies",
            data.get("allergies") or [],
            RED,
            RED_LIGHT,
            "No allergies recorded",
        ),
        (
            "Key conditions",
            data.get("conditions") or [],
            VIOLET,
            VIOLET_LIGHT,
            "No conditions recorded",
        ),
        (
            "Recent abnormal labs",
            data.get("recent_abnormal_labs") or [],
            ACCENT,
            ACCENT_LIGHT,
            "No abnormal labs recorded",
        ),
    ]
    for title, items, accent, accent_light, empty_text in sections:
        y = _draw_section(page, fitz, y, title, items, accent, accent_light, empty_text)

    # Footer.
    footer = (
        "Generated by MediMind from uploaded records. This is a summary, not a diagnosis — "
        "confirm every item with your clinician. In an emergency, contact your local "
        "emergency service."
    )
    wrapped_footer = _wrap(footer, BODY_FONT, 7.5, CONTENT_WIDTH, fitz)
    fy = PAGE_HEIGHT - FOOTER_RESERVE + 10.0
    for line in wrapped_footer:
        page.insert_text((MARGIN, fy), line, fontname=BODY_FONT, fontsize=7.5, color=MUTED)
        fy += 9.0

    try:
        return doc.tobytes(garbage=3, deflate=True)
    finally:
        doc.close()


def build_health_passport_pdf(
    timeline: Dict[str, Any],
    cross_check: Optional[Dict[str, Any]] = None,
    lab_trends: Optional[Dict[str, Any]] = None,
    patient_name: Optional[str] = None,
    workspace_name: Optional[str] = None,
) -> bytes:
    """End-to-end: record -> passport data -> single-page PDF bytes."""
    data = build_passport_data(
        timeline,
        cross_check=cross_check,
        lab_trends=lab_trends,
        patient_name=patient_name,
        workspace_name=workspace_name,
    )
    return render_passport_pdf(data)
