/**
 * Copy for the About / Technical Overview page.
 *
 * Every claim here was verified against the repository — routes against
 * `backend/api.py`, pipeline stages against `medical_extractor.py` and
 * `retrieval.py`, storage against `db.py` / `storage.py` / `vector_store.py`.
 * If a capability is not implemented it is either omitted or explicitly
 * labelled as planned. Please re-verify before editing.
 *
 * Kept in its own module (rather than inside `en.ts`) so a translator can
 * work on the documentation copy without touching product UI strings. Adding
 * a locale means adding a sibling dictionary — no component changes.
 */
export const aboutEn = {
  // ---- Shell -------------------------------------------------------------
  nav: "About MediMind",
  navAria: "About MediMind — how the product works",
  eyebrow: "Technical overview",
  title: "About MediMind",
  lede: "MediMind is an AI-powered medical document intelligence platform that helps you organise, understand, and explore your medical records — while keeping every AI answer grounded in the documents you uploaded.",
  onThisPage: "On this page",
  backToDashboard: "Back to dashboard",

  // ---- 1. Overview -------------------------------------------------------
  overview: {
    id: "overview",
    title: "Overview",
    principlesTitle: "What that means in practice",
    principles: [
      {
        title: "It works from your records",
        body: "MediMind has no medical knowledge base of its own to answer from. Everything it shows you is extracted from the documents you upload.",
      },
      {
        title: "Answers are grounded",
        body: "Ask AI answers only from passages retrieved out of your own records. When your records don't cover a question, it says so instead of guessing.",
      },
      {
        title: "Every answer shows its evidence",
        body: "Answers cite the source document, and the page where the record has one. Citations are verified server-side — a filename the model invents is dropped before you ever see it.",
      },
      {
        title: "It is not a doctor",
        body: "MediMind does not diagnose, and will not tell you to start, stop, or change a medication. It organises what your records say and points you to a professional.",
      },
      {
        title: "You stay in control",
        body: "A workspace is tied to your browser — no account, no sign-up. You can start a fresh workspace or reset your data at any time from the sidebar.",
      },
    ],
  },

  // ---- 2. Key features ---------------------------------------------------
  features: {
    id: "features",
    title: "Key features",
    subtitle: "Each of these is implemented and reachable from the sidebar today.",
    items: [
      {
        icon: "document",
        title: "Medical document intelligence",
        body: "Upload PDFs and photos of prescriptions, lab reports, and discharge summaries. MediMind extracts structured information — medications, lab values, allergies, and clinical notes — and links every field back to the file it came from.",
        points: [
          "Digital PDFs are read from their text layer; scans and photos go through vision OCR",
          "Non-medical files (receipts, boarding passes) are detected and rejected",
          "Low-confidence fields are flagged rather than presented as certain",
        ],
      },
      {
        icon: "pill",
        title: "Medication tracking",
        body: "Every medication found across your documents, grouped by active ingredient so the same drug under two brand names lines up as one entry.",
        points: [
          "Current medications separated from historical ones",
          "Dosage and frequency normalised for comparison across visits",
          "Each entry traceable to its source document",
        ],
      },
      {
        icon: "beaker",
        title: "Lab trend analysis",
        body: "Lab values compared across dates to show direction of travel, computed arithmetically from the extracted numbers rather than generated by a model.",
        points: [
          "Direction, flag sequence, and the point a value crossed out of range",
          "Values approaching a reference boundary flagged before they cross",
          "Sparkline plotted against the reference band",
        ],
      },
      {
        icon: "shield",
        title: "Safety analysis",
        body: "A cross-check across your whole medication timeline, surfacing things that are hard to spot when records live in separate documents.",
        points: [
          "Potential drug interactions with a severity and confidence",
          "Duplicate prescriptions, including exact duplicates detected in code",
          "Conflicting dosages and instructions between visits",
          "Conflicts against allergies noted in your records",
        ],
      },
      {
        icon: "chat",
        title: "Grounded Ask AI",
        body: "Ask questions in plain language. MediMind retrieves the most relevant passages from your records and answers only from those.",
        points: [
          "Citations open the exact source document and page",
          "Invented citations are dropped and uncited answers capped in confidence",
          "Document text is treated as data, never as instructions to the model",
          "Conversations mode resolves follow-ups like \"was that safe?\"",
        ],
      },
      {
        icon: "location",
        title: "Find Care",
        body: "Search for nearby hospitals, clinics, pharmacies, laboratories, and doctors around a location you confirm on a map.",
        points: [
          "Optional specialty, suggested from your records but always yours to change",
          "Real facility names, ratings, hours, and distance where the directory publishes them",
          "Directory listings clearly marked as public data, not a MediMind recommendation",
        ],
      },
    ],
  },

  // ---- 3. System architecture -------------------------------------------
  architecture: {
    id: "architecture",
    title: "System architecture",
    subtitle: "The layers a request passes through, and the technology behind each.",
    diagramLabel: "MediMind system architecture, from browser to AI providers",
    textAlternativeTitle: "Architecture described in text",
    layers: [
      {
        name: "Frontend",
        tech: "React 18 · TypeScript · Vite · Tailwind CSS · React Router · Leaflet",
        body: "A single-page app. Find Care is lazy-loaded so its map libraries aren't in the initial bundle. No API keys ever reach the browser.",
      },
      {
        name: "API",
        tech: "FastAPI · Uvicorn · JWT (HS256)",
        body: "One authenticated REST surface. Every route except the health check requires a bearer token plus a matching user id header. Long-running AI work is dispatched to worker threads so a slow answer never blocks other requests.",
      },
      {
        name: "Document processing",
        tech: "pdfplumber · PyMuPDF · Pillow · vision model",
        body: "PDFs with a text layer are parsed directly. Scans and photos are rendered to images and read by a vision model. A deterministic filter then rejects non-medical files before any expensive downstream work.",
      },
      {
        name: "Clinical data",
        tech: "Supabase (PostgreSQL) · Cloudinary",
        body: "Extracted documents and the derived patient snapshot are persisted per user. Original files are stored separately in per-user folders so structured data can link back to the source.",
      },
      {
        name: "Retrieval",
        tech: "Chroma or Supabase pgvector-style table · MiniLM or OpenAI embeddings",
        body: "The timeline is chunked into medication, lab, clinical-note, and allergy passages, embedded, and stored per patient. Embeddings run locally via ONNX MiniLM by default, so no embedding API key is required.",
      },
      {
        name: "AI generation",
        tech: "OpenAI-compatible providers (Groq or Gemini)",
        body: "Retrieved passages plus the question go to a chat model under a strict JSON schema. Keys stay server-side and the provider is swappable through configuration.",
      },
      {
        name: "Evidence",
        tech: "Server-side citation validation",
        body: "Before an answer is returned, its citations are checked against what was actually retrieved. Unsupported citations are removed and confidence is capped when nothing verifiable backs the answer.",
      },
    ],
  },

  // ---- 4. RAG pipeline ---------------------------------------------------
  pipeline: {
    id: "pipeline",
    title: "AI & RAG pipeline",
    subtitle: "What happens between uploading a document and reading a cited answer.",
    diagramLabel: "Retrieval-augmented generation pipeline, from document to cited answer",
    ingestTitle: "Ingestion — runs once per upload",
    answerTitle: "Answering — runs on every question",
    stages: [
      {
        phase: "ingest",
        title: "Document upload",
        body: "PDF, PNG, JPG, JPEG or WEBP. Uploads run synchronously by default, or as a background job you can poll when enabled.",
      },
      {
        phase: "ingest",
        title: "Text extraction / OCR",
        body: "A PDF with a text layer is parsed directly. Anything else is rendered page by page and read by a vision model.",
      },
      {
        phase: "ingest",
        title: "Medical extraction",
        body: "One model call per document returns structured JSON under a strict schema: medications, lab results, allergies, clinical notes, and a per-field confidence.",
      },
      {
        phase: "ingest",
        title: "Relevance filter",
        body: "A deterministic check on the extracted structure rejects non-medical files. No extra model call, and it runs before any expensive downstream work.",
      },
      {
        phase: "ingest",
        title: "Structured clinical data",
        body: "Documents merge into one chronological timeline, with flattened medication and lab rollups that the dashboard, labs, and safety views all read from.",
      },
      {
        phase: "ingest",
        title: "Chunking & embeddings",
        body: "The timeline becomes one passage per medication, lab result, clinical note, and allergy list. Each is embedded and stored under your patient key with deterministic ids, so re-indexing updates in place.",
      },
      {
        phase: "answer",
        title: "Retrieval",
        body: "Your question is embedded and the closest passages from your records are fetched. In Conversations, an ambiguous follow-up is first rewritten into a self-contained query.",
      },
      {
        phase: "answer",
        title: "Answer generation",
        body: "Retrieved passages are fenced as untrusted data and sent with the question. The model must answer only from them and return strict JSON.",
      },
      {
        phase: "answer",
        title: "Citation validation",
        body: "Citations are checked against what was retrieved. Invented filenames are dropped, dates corrected, page numbers attached from chunk metadata, and confidence capped when nothing supports the answer.",
      },
    ],
    selfHealTitle: "Self-healing index",
    selfHealBody: "If the vector index is empty but your documents are still on record — after a redeploy without a persistent volume, for example — MediMind rebuilds the index from those saved documents and answers anyway, rather than incorrectly reporting that you have no records.",
  },

  // ---- 5. Data flow ------------------------------------------------------
  dataFlow: {
    id: "data-flow",
    title: "Data flow",
    subtitle: "Where your information goes, and what reads it back.",
    diagramLabel: "How a medical record flows from upload through to each feature",
    youTitle: "You upload a record",
    youBody: "A prescription, lab report, or discharge summary — as a PDF or a photo.",
    storeTitle: "It is stored and read",
    storeBody: "The original file is kept so you can always open it. A structured copy of what it contains is saved to your workspace.",
    useTitle: "Features read that structured copy",
    useBody: "Nothing re-reads your original files on every visit; each feature works from the extracted record.",
    consumers: [
      { name: "Dashboard", body: "An at-a-glance summary of your whole record." },
      { name: "Medical Records", body: "Each document, with the original alongside what was found in it." },
      { name: "Medications", body: "Current and historical medications, grouped by ingredient." },
      { name: "Lab Results", body: "Values compared across dates, with trends and reference bands." },
      { name: "Timeline", body: "Your visits in chronological order." },
      { name: "Safety Alerts", body: "Interactions, duplicates, and dosage conflicts across visits." },
      { name: "Ask AI", body: "Questions answered from retrieved passages, with citations." },
    ],
    groundingTitle: "Why Ask AI can only answer from your records",
    groundingBody: "Ask AI never queries the open internet or a general medical database. Its input is limited to passages retrieved from your own uploaded records, and its output is checked against those passages before you see it. If your records don't contain the answer, it tells you they don't.",
  },

  // ---- 6. Security & privacy --------------------------------------------
  security: {
    id: "security",
    title: "Security & privacy",
    subtitle: "What is implemented today — and, honestly, what is not.",
    implementedTitle: "Implemented",
    implemented: [
      {
        title: "Browser-local workspace",
        body: "No account, no email, no password. A workspace is created anonymously and its credentials live in your browser's local storage.",
      },
      {
        title: "Signed tokens on every request",
        body: "Every route except the health check requires a JWT signed with a server-side secret, verified on each call. A mismatched user id header is rejected.",
      },
      {
        title: "Per-user data isolation",
        body: "Documents, snapshots, and vector chunks are all keyed by user id, and every read is filtered by the id from your verified token. Vector collection names include a hash of that id so two users can never share one.",
      },
      {
        title: "Server-side credentials",
        body: "AI provider, maps, storage, and database keys stay on the server. The browser never receives them, and provider errors are redacted before being returned.",
      },
      {
        title: "Prompt-injection resistance",
        body: "Text retrieved from your documents is fenced as untrusted data, and instruction-shaped phrasing inside it is defanged, so a malicious document cannot redirect the assistant.",
      },
      {
        title: "Grounded, non-prescriptive answers",
        body: "The assistant refuses to diagnose or to advise changing a medication, states plainly when something is absent from your records, and has its citations validated server-side.",
      },
      {
        title: "Medical disclaimers where decisions happen",
        body: "Safety analysis, lab trends, and care listings each carry a disclaimer, and directory results are explicitly marked as public listings rather than recommendations.",
      },
    ],
    notYetTitle: "Not claimed",
    notYetBody: "Being straight about the boundaries matters more than a longer list:",
    notYet: [
      "No regulatory compliance certification — MediMind is not HIPAA or GDPR certified.",
      "No application-level encryption of record contents beyond the transport security and at-rest encryption the hosting providers supply.",
      "Anonymous workspace tokens are long-lived and held in browser storage; anyone with access to your browser profile can reach that workspace.",
      "Conversation sessions are held in server memory and are lost when the API restarts.",
    ],
    plannedTitle: "Planned",
    planned: [
      "Optional account linking so a workspace can be recovered on another device.",
      "Server-side session persistence for conversations.",
      "Per-document sharing controls.",
    ],
  },

  // ---- 7. API ------------------------------------------------------------
  api: {
    id: "api",
    title: "API overview",
    subtitle: "The public REST surface. Every route below is authenticated unless noted.",
    authTitle: "Authentication",
    authBody: "Requests carry an Authorization bearer token plus a matching X-User-Id header. A workspace token is issued by the anonymous session endpoint — no credentials are required from you.",
    groups: [
      {
        name: "Documents",
        endpoints: [
          { method: "POST", path: "/api/v1/documents", body: "Upload and process one or more medical documents. Returns the updated record, or a job id in async mode." },
          { method: "GET", path: "/api/v1/timeline", body: "Every extracted document, in chronological order, with medication and lab rollups." },
          { method: "GET", path: "/api/v1/patient-snapshot", body: "Timeline, safety cross-check, and lab trends in one response — what the dashboard loads." },
        ],
      },
      {
        name: "Processing jobs",
        endpoints: [
          { method: "GET", path: "/api/v1/jobs", body: "List recent upload jobs for this workspace." },
          { method: "GET", path: "/api/v1/jobs/{job_id}", body: "Poll one job's progress, per file." },
        ],
      },
      {
        name: "Clinical analysis",
        endpoints: [
          { method: "GET", path: "/api/v1/cross-check", body: "Safety analysis: interactions, duplicates, dosage conflicts, allergy conflicts." },
          { method: "GET", path: "/api/v1/lab-trends", body: "Per-test direction, threshold crossings, and plain-language explanations." },
        ],
      },
      {
        name: "Ask AI",
        endpoints: [
          { method: "POST", path: "/api/v1/qa", body: "Ask one question, answered from retrieved passages with validated citations." },
          { method: "POST", path: "/api/v1/sessions", body: "Start a conversation that remembers previous turns." },
          { method: "POST", path: "/api/v1/sessions/{session_id}/messages", body: "Ask a follow-up within a conversation; ambiguous references are resolved from history." },
          { method: "GET", path: "/api/v1/sessions/{session_id}", body: "Full transcript of a conversation." },
          { method: "DELETE", path: "/api/v1/sessions/{session_id}", body: "End a conversation and discard its history." },
        ],
      },
      {
        name: "Find Care",
        endpoints: [
          { method: "GET", path: "/api/v1/care/facilities", body: "Public healthcare listings near a point or place, filtered by type, radius, and optional specialty." },
        ],
      },
      {
        name: "Workspace",
        endpoints: [
          { method: "POST", path: "/api/v1/anonymous/session", body: "Create an anonymous workspace and issue its token. No authentication required." },
          { method: "GET", path: "/api/v1/health", body: "Service health. No authentication required." },
        ],
      },
    ],
  },

  // ---- Footer ------------------------------------------------------------
  disclaimerTitle: "A reminder",
  disclaimerBody: "MediMind helps you organise and explore your own medical records. It does not diagnose, prescribe, or replace professional medical advice. Always consult a qualified clinician or pharmacist before acting on anything you read here. In an emergency, contact your local emergency service immediately.",
} as const;

export type AboutCopy = typeof aboutEn;
